export const REQUEST_BODY_INDEX = Symbol('REQUEST_BODY_INDEX');
export const REQUEST_PARAM_INDEX = Symbol('REQUEST_PARAM_INDEX');
export const REQUEST_PATH_VARIABLES_INDEX = Symbol('REQUEST_PATH_VARIABLES_INDEX');
